"""Step 9: LLM Analysis Layer — streams Claude API response over WebSocket.

In stub mode (no ANTHROPIC_API_KEY), yields a mock token stream.
"""
import asyncio
import os
from typing import AsyncIterator

MOCK_RESPONSE = """\
**Additional Theory 1: Regulatory Cost Pass-Through Restrictions**
Brazilian industrial companies face sector-specific pricing regulations that may limit the ability to pass input cost increases to customers. If government price controls or long-term supply contracts prevented full pass-through of naphtha cost spikes, the structural COGS increase would persist even after feedstock costs normalized. **Confirming data:** Contract pricing terms with key customers, regulatory filings related to pricing.

**Additional Theory 2: Working Capital Compression Masking Underlying Economics**
Braskem's financial restructuring and debt covenant pressures may have led management to optimize for cash over margin — accepting lower-margin contracts to maintain volume and service debt. This would show up as COGS/Revenue deterioration without a proportional decline in production efficiency. **Confirming data:** Management commentary on margin vs. volume trade-offs, contract backlog by margin tier.

**Additional Theory 3: Consolidation of Loss-Making Subsidiaries**
The step-up in COGS ratio may reflect the full consolidation of previously equity-accounted subsidiaries (notably Braskem Idesa) onto the balance sheet. A loss-making consolidated entity contributes its full COGS to the numerator without proportional revenue contribution. **Confirming data:** Segment elimination entries in consolidation workpapers, Braskem Idesa standalone financials.

**Most Likely Hypothesis Assessment:**
Among the provided hypotheses, H1 (Naphtha feedstock cost disadvantage) and H2 (China oversupply compressing spreads) are most likely to be co-primary causes. The timing correlation — COGS ratio deteriorated most sharply in 2022-2023, exactly when Chinese PE/PP export pressure intensified and naphtha tracked Brent above $100/bbl — is compelling. H3 (BRL depreciation) is a reinforcing factor, not a primary driver.

**Recommended Analytical Next Steps:**
1. Obtain 3.02.x sub-account COGS breakdown to isolate feedstock vs. conversion costs
2. Compare Braskem's COGS/Revenue trajectory vs. Unipar Carbocloro (comparable Brazilian petrochemical) to test peer divergence
3. Build a bridge analysis: FX impact + naphtha price impact + volume impact = explained COGS change vs. residual
"""


async def stream(payload: dict, config) -> AsyncIterator[str]:
    """Yields tokens. In stub mode, simulates streaming from mock text."""
    api_key = os.getenv("ANTHROPIC_API_KEY", "")

    if not api_key:
        words = MOCK_RESPONSE.split(" ")
        for i, word in enumerate(words):
            token = word if i == len(words) - 1 else word + " "
            yield token
            await asyncio.sleep(0.03)
        return

    import anthropic
    client = anthropic.AsyncAnthropic(api_key=api_key)

    finding  = payload.get("finding", {})
    company  = payload.get("company_context", {})
    macro    = payload.get("macro_context", [])
    language = payload.get("language", "en")
    hypotheses = payload.get("hypotheses", [])  # top-3 from Step 7

    lang_str = "Portuguese (Brazilian)" if language == "pt-br" else "English"

    system_prompt = (
        "You are a senior financial analyst examining public financial data from Brazilian "
        "companies filed with the CVM (Securities Commission). You have expertise in "
        "petrochemical industry economics, cost structure analysis, and EBITDA driver "
        "decomposition.\n\n"
        "Your task: Given a specific analytical finding and its supporting data, generate "
        "additional theories and analytical angles that could explain the pattern.\n\n"
        "You have been provided with structured hypotheses already generated by the "
        "analytical pipeline. BUILD ON THESE — do not repeat them. Instead:\n"
        "1. Identify 2-3 ADDITIONAL theories the pipeline may have missed\n"
        "2. For each theory, explain the specific mechanism and what data would confirm it\n"
        "3. Highlight which of the provided hypotheses you consider most likely and why\n"
        "4. Suggest specific analytical next steps\n\n"
        "Be specific and quantitative. Reference the actual numbers from the finding. "
        f"Write in {lang_str}."
    )

    # Build hypotheses context block
    hyp_lines = []
    for h in hypotheses[:3]:
        mechanism_short = h.get("mechanism", "")[:120].rstrip() + "..."
        hyp_lines.append(f"- {h['id']}: {h['theory']} — {mechanism_short}")
    hyp_block = "\n".join(hyp_lines) if hyp_lines else "(Step 7 not run — no prior hypotheses)"

    data_points_str = "\n".join(
        f"  {k}: {v}" for k, v in (finding.get("data_points") or {}).items()
    ) or "  (none)"

    user_prompt = (
        f"## Finding\n{finding.get('description', '')}\n\n"
        f"## Supporting Data\n{data_points_str}\n\n"
        f"## Macro Context\n{', '.join(macro) if macro else 'None provided'}\n\n"
        f"## Existing Hypotheses (from analytical pipeline)\n{hyp_block}\n\n"
        f"## Company Context\n"
        f"Company: {company.get('name')} ({company.get('sector')})\n"
        f"Analysis period: {company.get('period')}\n\n"
        f"Generate your analysis."
    )

    async with client.messages.stream(
        model="claude-sonnet-4-6",
        max_tokens=1500,
        system=system_prompt,
        messages=[{"role": "user", "content": user_prompt}],
    ) as stream_obj:
        async for text in stream_obj.text_stream:
            yield text
