"""Markdown context export — assembles full analysis pipeline results into a
single .md file suitable for upload to external LLMs.

All data comes from cached step results; no new computation is performed.
"""
import json
from datetime import date
from pathlib import Path

from cache_utils import load_cache


# ---------------------------------------------------------------------------
# Bilingual label tables
# ---------------------------------------------------------------------------

_LABELS = {
    "en": {
        "title": "Cygnus Financial Signal Analysis",
        "analysis_period": "Analysis Period",
        "data_source": "Data Source",
        "generated": "Generated",
        "risk_score": "Risk Score",
        "company_overview": "Company Overview",
        "company": "Company",
        "sector": "Sector",
        "country": "Country (Currency)",
        "statements_analyzed": "Statements Analyzed",
        "periods": "Periods",
        "key_financial_metrics": "Key Financial Metrics",
        "profitability_annual": "Profitability (Annual)",
        "balance_sheet_annual": "Balance Sheet (Annual)",
        "cash_flow_annual": "Cash Flow (Annual)",
        "metric": "Metric",
        "pattern_detection": "Pattern Detection Results",
        "risk_assessment": "Risk Assessment",
        "algorithms_run": "Algorithms Run",
        "findings": "Findings",
        "profitability_findings": "Profitability Findings",
        "balance_sheet_findings": "Balance Sheet Findings",
        "cash_flow_findings": "Cash Flow Findings",
        "cross_module_diagnoses": "Cross-Module Diagnoses",
        "contributing_signals": "Contributing signals",
        "estimated_impact": "Estimated Impact",
        "ai_analysis": "AI Industry Specialist Analysis",
        "macro_context": "Macro Context",
        "hypotheses_by_group": "Hypotheses by Finding Group",
        "top_hypothesis": "Top hypothesis",
        "confidence": "Confidence",
        "data_gaps": "Data Gaps",
        "executive_summary": "Executive Summary",
        "key_findings_table": "Key Findings Table",
        "finding": "Finding",
        "severity": "Severity",
        "evidence": "Evidence",
        "next_step": "Next Step",
        "suggested_questions": "Suggested Follow-Up Questions",
        "footer": "Generated by Cygnus — Decision Intelligence for CFOs",
        "disclaimer": "AI-generated analysis. Domain expert review recommended.",
        "income_statement": "Income Statement",
        "balance_sheet": "Balance Sheet",
        "cash_flow_statement": "Cash Flow Statement",
        "annual": "annual",
        "quarterly": "quarterly",
        "gross_margin": "Gross Margin %",
        "ebit_margin": "EBIT Margin %",
        "ebitda_margin": "EBITDA Margin %",
        "cogs_revenue": "COGS / Revenue %",
        "sga_revenue": "SG&A / Revenue %",
        "current_ratio": "Current Ratio",
        "quick_ratio": "Quick Ratio",
        "net_debt": "Net Debt (BRL M)",
        "debt_ebitda": "Debt/EBITDA",
        "return_on_assets": "Return on Assets %",
        "return_on_equity": "Return on Equity %",
        "operating_cash_flow": "Operating Cash Flow (BRL M)",
        "free_cash_flow": "Free Cash Flow (BRL M)",
        "capex_revenue": "CapEx / Revenue %",
        "ocf_net_income": "OCF / Net Income",
        "brazil_brl": "Brazil (BRL)",
        "petrochemical": "Petrochemical",
        "value_distribution_findings": "Value Distribution (DVA) Findings",
        "equity_findings": "Equity Movements (DMPL) Findings",
        "dva_distribution_title": "DVA — Value Distribution",
        "dmpl_equity_title": "DMPL — Equity Movements",
        "dva_employees": "Employees %",
        "dva_government": "Government %",
        "dva_lenders": "Lenders %",
        "dva_shareholders": "Shareholders %",
        "dva_va_margin": "VA Margin %",
        "dva_input_intensity": "Input Intensity %",
        "dmpl_opening_equity": "Opening Equity (BRL M)",
        "dmpl_closing_equity": "Closing Equity (BRL M)",
        "dmpl_net_income": "Net Income (BRL M)",
        "dmpl_dividends": "Dividends (BRL M)",
        "dmpl_oci": "OCI (BRL M)",
    },
    "pt-br": {
        "title": "Análise de Sinais Financeiros Cygnus",
        "analysis_period": "Período de Análise",
        "data_source": "Fonte de Dados",
        "generated": "Gerado",
        "risk_score": "Score de Risco",
        "company_overview": "Visão Geral da Empresa",
        "company": "Empresa",
        "sector": "Setor",
        "country": "País (Moeda)",
        "statements_analyzed": "Demonstrações Analisadas",
        "periods": "Períodos",
        "key_financial_metrics": "Métricas Financeiras Principais",
        "profitability_annual": "Rentabilidade (Anual)",
        "balance_sheet_annual": "Balanço Patrimonial (Anual)",
        "cash_flow_annual": "Fluxo de Caixa (Anual)",
        "metric": "Métrica",
        "pattern_detection": "Resultados da Detecção de Padrões",
        "risk_assessment": "Avaliação de Risco",
        "algorithms_run": "Algoritmos Executados",
        "findings": "Achados",
        "profitability_findings": "Achados de Rentabilidade",
        "balance_sheet_findings": "Achados do Balanço Patrimonial",
        "cash_flow_findings": "Achados do Fluxo de Caixa",
        "cross_module_diagnoses": "Diagnósticos Cross-Module",
        "contributing_signals": "Sinais contribuintes",
        "estimated_impact": "Impacto Estimado",
        "ai_analysis": "Análise do Especialista Setorial IA",
        "macro_context": "Contexto Macro",
        "hypotheses_by_group": "Hipóteses por Grupo de Achados",
        "top_hypothesis": "Principal hipótese",
        "confidence": "Confiança",
        "data_gaps": "Lacunas de Dados",
        "executive_summary": "Sumário Executivo",
        "key_findings_table": "Tabela de Principais Achados",
        "finding": "Achado",
        "severity": "Gravidade",
        "evidence": "Evidência",
        "next_step": "Próximo Passo",
        "suggested_questions": "Perguntas Sugeridas de Acompanhamento",
        "footer": "Gerado por Cygnus — Inteligência de Decisão para CFOs",
        "disclaimer": "Análise gerada por IA. Revisão por especialista de domínio recomendada.",
        "income_statement": "Demonstração de Resultado",
        "balance_sheet": "Balanço Patrimonial",
        "cash_flow_statement": "Demonstração de Fluxo de Caixa",
        "annual": "anuais",
        "quarterly": "trimestrais",
        "gross_margin": "Margem Bruta %",
        "ebit_margin": "Margem EBIT %",
        "ebitda_margin": "Margem EBITDA %",
        "cogs_revenue": "CPV / Receita %",
        "sga_revenue": "SG&A / Receita %",
        "current_ratio": "Índice de Liquidez Corrente",
        "quick_ratio": "Índice de Liquidez Seca",
        "net_debt": "Dívida Líquida (BRL M)",
        "debt_ebitda": "Dívida/EBITDA",
        "return_on_assets": "Retorno sobre Ativos %",
        "return_on_equity": "Retorno sobre Patrimônio %",
        "operating_cash_flow": "Fluxo de Caixa Operacional (BRL M)",
        "free_cash_flow": "Fluxo de Caixa Livre (BRL M)",
        "capex_revenue": "CapEx / Receita %",
        "ocf_net_income": "FCO / Lucro Líquido",
        "brazil_brl": "Brasil (BRL)",
        "petrochemical": "Petroquímica",
        "value_distribution_findings": "Achados de Distribuição de Valor (DVA)",
        "equity_findings": "Achados de Movimentos do Patrimônio (DMPL)",
        "dva_distribution_title": "DVA — Distribuição de Valor",
        "dmpl_equity_title": "DMPL — Movimentos do Patrimônio",
        "dva_employees": "Empregados %",
        "dva_government": "Governo %",
        "dva_lenders": "Financiadores %",
        "dva_shareholders": "Acionistas %",
        "dva_va_margin": "Margem VA %",
        "dva_input_intensity": "Intensidade de Insumos %",
        "dmpl_opening_equity": "PL Inicial (BRL M)",
        "dmpl_closing_equity": "PL Final (BRL M)",
        "dmpl_net_income": "Lucro Líquido (BRL M)",
        "dmpl_dividends": "Dividendos (BRL M)",
        "dmpl_oci": "OCI (BRL M)",
    },
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _L(lang: str) -> dict:
    return _LABELS.get(lang, _LABELS["en"])


def _fmt(v, decimals: int = 1) -> str:
    if v is None:
        return "—"
    try:
        f = float(v)
        return f"{f:,.{decimals}f}"
    except (TypeError, ValueError):
        return str(v)


def _fmt_brl_b(v) -> str:
    """Format a BRL value in thousands as 'R$ X.X B'."""
    if v is None:
        return "—"
    try:
        b = float(v) / 1_000_000
        return f"R$ {b:,.1f} B"
    except (TypeError, ValueError):
        return str(v)


def _impact_str(raw) -> str:
    """estimated_impact may be a dict {formatted: '~R$ 3.2 bi'} or a plain string."""
    if raw is None:
        return "—"
    if isinstance(raw, dict):
        return raw.get("formatted") or str(raw.get("value_brl", "—"))
    return str(raw)


def _year(period_str: str) -> str:
    if period_str and len(str(period_str)) >= 4:
        return str(period_str)[:4]
    return str(period_str)


def _annual_only(series: list) -> list:
    annual = [r for r in series if r.get("granularity") in ("annual", "dfp", None)]
    return annual if annual else series


def _mk_table(headers: list[str], rows: list[list[str]]) -> str:
    """Build a markdown table string."""
    sep = "| " + " | ".join(["---"] * len(headers)) + " |"
    header_row = "| " + " | ".join(headers) + " |"
    data_rows = ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]
    return "\n".join([header_row, sep] + data_rows)


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------

def _section_header(t: dict, step1: dict | None, company_name: str, lang: str) -> str:
    today = date.today().isoformat()
    periods = ""
    if step1:
        dr = step1.get("date_range", {})
        start = _year(dr.get("start", ""))
        end   = _year(dr.get("end", ""))
        if start and end:
            periods = f"{start}–{end}"

    lines = [
        f"# {t['title']} — {company_name}",
        "",
        f"{t['analysis_period']}: {periods}",
        f"{t['data_source']}: CVM Open Data Portal",
        f"{t['generated']}: {today}",
        "",
        "---",
        "",
    ]
    return "\n".join(lines)


def _section_company_overview(t: dict, step1: dict | None, step4: dict | None) -> str:
    # Derive sector from enrichment data or step6 if available
    ts = (step4 or {}).get("time_series", [])
    annual_count = len(ts)
    cf_series = (step4 or {}).get("cash_flow_series", [])

    stmts = ", ".join([t["income_statement"], t["balance_sheet"], t["cash_flow_statement"]])

    lines = [
        f"## {t['company_overview']}",
        "",
        f"**{t['company']}:** {(step1 or {}).get('company_name', '—')}",
        f"**{t['country']}:** {t['brazil_brl']}",
        f"**{t['statements_analyzed']}:** {stmts}",
        f"**{t['periods']}:** {annual_count} {t['annual']}",
        "",
        "---",
        "",
    ]
    return "\n".join(lines)


def _section_metrics(t: dict, step4: dict | None) -> str:
    if not step4:
        return ""

    ts = _annual_only(step4.get("time_series", []))
    bs = _annual_only(step4.get("balance_sheet_series", []))
    cf = _annual_only(step4.get("cash_flow_series", []))

    if not ts:
        return ""

    periods = [_year(r.get("period", "")) for r in ts]

    lines = [f"## {t['key_financial_metrics']}", ""]

    # Profitability table
    lines.append(f"### {t['profitability_annual']}")
    lines.append("")
    prof_metrics = [
        (t["gross_margin"],   "Gross_Margin_pct",  1),
        (t["ebit_margin"],    "EBIT_Margin_pct",   1),
        (t["ebitda_margin"],  "EBITDA_Margin_pct", 1),
        (t["cogs_revenue"],   "COGS_pct_Revenue",  1),
        (t["sga_revenue"],    "SGA_pct_Revenue",   1),
    ]
    headers = [t["metric"]] + periods
    rows = []
    for label, key, dec in prof_metrics:
        row = [label] + [_fmt(r.get(key), dec) for r in ts]
        rows.append(row)
    lines.append(_mk_table(headers, rows))
    lines.append("")

    # Balance sheet table
    if bs:
        lines.append(f"### {t['balance_sheet_annual']}")
        lines.append("")
        bs_periods = [_year(r.get("period", "")) for r in bs]
        bs_headers = [t["metric"]] + bs_periods
        bs_metrics = [
            (t["current_ratio"],    "current_ratio",    2, False),
            (t["quick_ratio"],      "quick_ratio",      2, False),
            (t["net_debt"],         "net_debt",         1, True),
            (t["debt_ebitda"],      "debt_to_ebitda",   1, False),
            (t["return_on_assets"], "return_on_assets", 1, False),
            (t["return_on_equity"], "return_on_equity", 1, False),
        ]
        bs_rows = []
        for label, key, dec, is_brl in bs_metrics:
            row = [label] + [_fmt_brl_b(r.get(key)) if is_brl else _fmt(r.get(key), dec) for r in bs]
            bs_rows.append(row)
        lines.append(_mk_table(bs_headers, bs_rows))
        lines.append("")

    # Cash flow table
    if cf:
        lines.append(f"### {t['cash_flow_annual']}")
        lines.append("")
        cf_periods = [_year(r.get("period", "")) for r in cf]
        cf_headers = [t["metric"]] + cf_periods
        cf_metrics = [
            (t["operating_cash_flow"], "operating_cash_flow", 1, True),
            (t["free_cash_flow"],      "free_cash_flow",      1, True),
            (t["capex_revenue"],       "capex_to_revenue",    1, False),
            (t["ocf_net_income"],      "ocf_to_net_income",   2, False),
        ]
        cf_rows = []
        for label, key, dec, is_brl in cf_metrics:
            row = [label] + [_fmt_brl_b(r.get(key)) if is_brl else _fmt(r.get(key), dec) for r in cf]
            cf_rows.append(row)
        lines.append(_mk_table(cf_headers, cf_rows))
        lines.append("")

    lines += ["---", ""]
    return "\n".join(lines)


def _section_dva_dmpl(t: dict, step4: dict | None) -> str:
    """Compact DVA distribution + DMPL equity movements tables."""
    if not step4:
        return ""

    dva_series = _annual_only(step4.get("dva_series", []))
    dmpl_series = _annual_only(step4.get("dmpl_series", []))

    if not dva_series and not dmpl_series:
        return ""

    lines = []

    if dva_series:
        lines.append(f"### {t['dva_distribution_title']}")
        lines.append("")
        dva_periods = [_year(r.get("period", "")) for r in dva_series]
        dva_headers = [t["metric"]] + dva_periods
        dva_metrics = [
            (t["dva_employees"],       "employees_pct",    1),
            (t["dva_government"],      "government_pct",   1),
            (t["dva_lenders"],         "lenders_pct",      1),
            (t["dva_shareholders"],    "shareholders_pct", 1),
            (t["dva_va_margin"],       "va_margin_pct",    1),
            (t["dva_input_intensity"], "input_intensity_pct", 1),
        ]
        dva_rows = []
        for label, key, dec in dva_metrics:
            row = [label] + [_fmt(r.get(key), dec) for r in dva_series]
            dva_rows.append(row)
        lines.append(_mk_table(dva_headers, dva_rows))
        lines.append("")

    if dmpl_series:
        lines.append(f"### {t['dmpl_equity_title']}")
        lines.append("")
        dmpl_periods = [_year(r.get("period", "")) for r in dmpl_series]
        dmpl_headers = [t["metric"]] + dmpl_periods
        dmpl_metrics = [
            (t["dmpl_opening_equity"], "opening_equity", True),
            (t["dmpl_net_income"],     "net_income",     True),
            (t["dmpl_dividends"],      "dividends",      True),
            (t["dmpl_oci"],            "oci",            True),
            (t["dmpl_closing_equity"], "closing_equity", True),
        ]
        dmpl_rows = []
        for label, key, is_brl in dmpl_metrics:
            row = [label] + [_fmt_brl_b(r.get(key)) if is_brl else _fmt(r.get(key)) for r in dmpl_series]
            dmpl_rows.append(row)
        lines.append(_mk_table(dmpl_headers, dmpl_rows))
        lines.append("")

    if lines:
        lines += ["---", ""]
    return "\n".join(lines)


def _section_auditor_assessment(t: dict, step5: dict | None, lang: str) -> str:
    """Auditor Assessment section for markdown export."""
    if not step5:
        return ""
    assess = step5.get("auditor_assessment") or {}
    if not assess.get("available") or not assess.get("opinions"):
        return ""

    is_pt = lang == "pt"
    title = "## Avaliação do Auditor\n\n" if is_pt else "## Auditor Assessment\n\n"
    lines = [title]

    opinions = assess.get("opinions", [])
    gc_detected = assess.get("going_concern_detected", False)
    gc_count    = assess.get("going_concern_count", 0)
    gc_total    = assess.get("total_reports", 0)
    gc_periods  = assess.get("going_concern_periods", [])

    if gc_detected:
        if is_pt:
            lines.append(
                f"⚠ **Ênfase em Continuidade Operacional** — O auditor incluiu ênfase em "
                f"continuidade operacional em {gc_count} de {gc_total} relatórios ({', '.join(str(p) for p in gc_periods)}).\n\n"
            )
        else:
            lines.append(
                f"⚠ **Going Concern Emphasis** — Auditor included going concern emphasis in "
                f"{gc_count} of {gc_total} reports ({', '.join(str(p) for p in gc_periods)}).\n\n"
            )

    _op_en = {"sem_ressalva": "Unqualified", "com_ressalva": "Qualified",
              "adverso": "Adverse", "abstencao": "Disclaimer", "unknown": "Unknown"}
    _op_pt = {"sem_ressalva": "Sem ressalva", "com_ressalva": "Com ressalva",
              "adverso": "Adverso", "abstencao": "Abstenção", "unknown": "Desconhecido"}
    op_lbl = _op_pt if is_pt else _op_en

    hdr_period = "Período" if is_pt else "Period"
    hdr_firm   = "Firma"   if is_pt else "Firm"
    hdr_opn    = "Opinião" if is_pt else "Opinion"
    hdr_gc     = "Continuidade" if is_pt else "Going Concern"
    hdr_km     = "Principais Assuntos" if is_pt else "Key Matters"

    lines.append(f"| {hdr_period} | {hdr_firm} | {hdr_opn} | {hdr_gc} | {hdr_km} |")
    lines.append("|--------|------|---------|---------------|-------------|")
    for op in opinions:
        year = str(op.get("period", ""))[:4] or str(op.get("year", ""))
        firm = op.get("auditor_firm", "Unknown")
        opn  = op_lbl.get(op.get("opinion_type", "unknown"), op.get("opinion_type", ""))
        gc   = ("⚠ " + ("Sim" if is_pt else "Yes")) if op.get("has_going_concern") else ("Não" if is_pt else "No")
        km   = ", ".join((op.get("key_audit_matters") or [])[:3]) or "—"
        lines.append(f"| {year} | {firm} | {opn} | {gc} | {km} |")

    lines.append("\n\n")
    return "".join(lines)


def _section_pattern_detection(t: dict, step6: dict | None) -> str:
    if not step6:
        return ""

    risk_score = step6.get("risk_score", "—")
    risk_level = step6.get("risk_level", "—")
    algorithms_run = step6.get("algorithms_run", "—")
    findings = step6.get("findings", [])

    lines = [
        f"## {t['pattern_detection']}",
        "",
        f"### {t['risk_assessment']}",
        f"- **{t['risk_score']}:** {risk_score}/100 ({risk_level})",
        f"- **{t['algorithms_run']}:** {algorithms_run}",
        f"- **{t['findings']}:** {len(findings)}",
        "",
    ]

    # Group findings by module
    modules = {
        "profitability":      (t["profitability_findings"], []),
        "balance_sheet":      (t["balance_sheet_findings"], []),
        "cash_flow":          (t["cash_flow_findings"], []),
        "value_distribution": (t["value_distribution_findings"], []),
        "equity":             (t["equity_findings"], []),
        "auditor":            (t.get("auditor_findings", "Auditor Findings"), []),
        "cross_module":       (t["cross_module_diagnoses"], []),
    }
    for f in findings:
        mod = (f.get("module") or "").lower().replace(" ", "_")
        if mod in modules:
            modules[mod][1].append(f)

    for mod_key, (mod_label, mod_findings) in modules.items():
        if not mod_findings:
            continue
        lines.append(f"### {mod_label}")
        lines.append("")
        for f in mod_findings:
            fid = f.get("id", "")
            pattern = f.get("pattern") or f.get("description", "")
            severity = f.get("severity", "")
            desc = f.get("description", "")
            impact = f.get("estimated_impact")
            signals = f.get("contributing_signals", [])

            lines.append(f"**{fid} — {pattern} ({severity})**")
            if desc and desc != pattern:
                lines.append(desc)
            if impact:
                lines.append(f"*{t['estimated_impact']}: {_impact_str(impact)}*")
            if signals:
                lines.append(f"*{t['contributing_signals']}: {', '.join(str(s) for s in signals)}*")
            lines.append("")

    lines += ["---", ""]
    return "\n".join(lines)


def _section_ai_analysis(t: dict, step7: dict | None) -> str:
    if not step7:
        return ""

    response_text = step7.get("response_text", "")
    if not response_text:
        return ""

    try:
        data = json.loads(response_text)
    except Exception:
        return ""

    macro = data.get("macro_context", {})
    modules = data.get("modules", {})

    lines = [f"## {t['ai_analysis']}", ""]

    # Macro context
    macro_text = macro.get("summary") or macro.get("context") or ""
    if isinstance(macro_text, str) and macro_text:
        lines.append(f"### {t['macro_context']}")
        lines.append("")
        lines.append(macro_text)
        lines.append("")

    # Hypotheses by module — using finding_groups structure
    lines.append(f"### {t['hypotheses_by_group']}")
    lines.append("")
    for mod_key in ("profitability", "balance_sheet", "cash_flow", "cross_module"):
        mod_data = modules.get(mod_key, {})
        if not mod_data:
            continue
        groups = mod_data.get("finding_groups", [])
        if not groups:
            continue
        lines.append(f"**{mod_key.replace('_', ' ').title()}**")
        lines.append("")
        for grp in groups[:3]:
            group_label = grp.get("group_label", "")
            top_h = grp.get("top_hypothesis", {})
            title = top_h.get("title", "")
            conf  = top_h.get("confidence", "")
            explanation = top_h.get("explanation", "")
            if title:
                lines.append(f"- **{group_label}**: {title} [{conf}]")
                if explanation:
                    lines.append(f"  - {explanation[:300]}")
        lines.append("")

    lines += ["---", ""]
    return "\n".join(lines)


def _section_executive_summary(t: dict, step8: dict | None) -> str:
    if not step8:
        return ""

    response_text = step8.get("response_text", "")
    if not response_text:
        return ""

    try:
        data = json.loads(response_text)
    except Exception:
        return ""

    exec_summary = data.get("executive_summary", "")
    key_findings = data.get("key_findings", [])
    next_step = data.get("next_step", "")
    suggested_questions = data.get("suggested_questions", [])

    lines = [f"## {t['executive_summary']}", ""]

    if exec_summary:
        lines.append(exec_summary)
        lines.append("")

    if key_findings:
        lines.append(f"### {t['key_findings_table']}")
        lines.append("")
        headers = ["#", t["finding"], t["severity"], t["evidence"]]
        rows = []
        for i, f in enumerate(key_findings, 1):
            finding_text = f.get("finding") or f.get("description", "")
            severity = f.get("severity", "")
            evidence = f.get("evidence", "")
            rows.append([str(i), finding_text, severity, evidence])
        lines.append(_mk_table(headers, rows))
        lines.append("")

    if next_step:
        lines.append(f"### {t['next_step']}")
        lines.append("")
        lines.append(next_step)
        lines.append("")

    if suggested_questions:
        lines.append(f"## {t['suggested_questions']}")
        lines.append("")
        for i, q in enumerate(suggested_questions, 1):
            lines.append(f"{i}. {q}")
        lines.append("")

    lines += ["---", ""]
    return "\n".join(lines)


def _footer(t: dict) -> str:
    return f"*{t['footer']}*\n*{t['disclaimer']}*\n"


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def build_markdown(
    company_name: str,
    lang: str,
    cache_dir: Path,
) -> str:
    """Assemble the full analysis context as a markdown string."""
    t = _L(lang)

    # Load cached step outputs
    step1_cache = load_cache(1, cache_dir, company_name=company_name)
    step4_cache = load_cache(4, cache_dir, company_name=company_name)
    step5_cache = load_cache(5, cache_dir, company_name=company_name)
    step6_cache = load_cache(6, cache_dir, company_name=company_name)
    step7_cache = load_cache(7, cache_dir, company_name=company_name)
    step8_cache = load_cache(8, cache_dir, company_name=company_name)

    step1 = (step1_cache or {}).get("data")
    step4 = (step4_cache or {}).get("data")
    step5 = (step5_cache or {}).get("data")
    step6 = (step6_cache or {}).get("data")
    step7 = (step7_cache or {}).get("data")
    step8 = (step8_cache or {}).get("data")

    # Add company_name to step1 data for use in overview section
    if step1 and not step1.get("company_name"):
        step1["company_name"] = company_name
    elif not step1:
        step1 = {"company_name": company_name}

    parts = [
        _section_header(t, step1, company_name, lang),
        _section_company_overview(t, step1, step4),
        _section_metrics(t, step4),
        _section_dva_dmpl(t, step4),
        _section_auditor_assessment(t, step5, lang),
        _section_pattern_detection(t, step6),
        _section_ai_analysis(t, step7),
        _section_executive_summary(t, step8),
        _footer(t),
    ]

    return "".join(parts)
